"""Managed AnyLLM local proxy support for anyllm variants.

anyllm-proxy is a foreground-only binary: no daemon mode, no pid file, and no
start/stop/status subcommands (unlike ccrouter, which delegates to the `ccr`
CLI). ccsilo therefore supervises the process itself here -- it launches the
proxy detached, writes its own pid file, and signals that pid to stop.

The proxy is a single shared local gateway: one instance on the listen port
serves every variant, so `start_anyllm` reuses an already-running proxy instead
of launching a second copy (the wrapper's runtime block does the same via a port
probe). The admin web UI token is generated by the proxy on first run when
ADMIN_TOKEN is unset and persisted to ~/.anyllm/.admin_token (override with
ANYLLM_HOME or ADMIN_TOKEN_PATH). That file is the single source of truth, so
ccsilo reads it rather than minting its own token; an externally started proxy
works identically.
"""

import os
import signal
import socket
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from ..providers import find_anyllm_proxy_binary

ANYLLM_PROVIDER_KEY = "anyllm"
ANYLLM_DEFAULT_PORT = 3000
ANYLLM_DEFAULT_ADMIN_URL = "http://127.0.0.1:3001/admin/"
ANYLLM_HEALTH_PATH = "/health"

_HEALTH_TIMEOUT = 0.5
_START_WAIT_SECONDS = 12.0
_STOP_WAIT_SECONDS = 5.0


@dataclass
class AnyllmResult:
    action: str
    ok: bool
    running: bool
    pid: Optional[int]
    detail: str
    log_path: str = ""


def anyllm_proxy_config(manifest: Dict) -> Optional[Dict[str, object]]:
    """Return the localProxy block when this is a usable AnyLLM proxy setup."""
    config = manifest.get("localProxy") if isinstance(manifest, dict) else None
    if not isinstance(config, dict):
        return None
    if not str(config.get("binary") or "").strip():
        return None
    if not isinstance(config.get("port"), int) or config["port"] < 1:
        return None
    return config


def _port(config: Dict[str, object]) -> int:
    port = config.get("port")
    return int(port) if isinstance(port, int) and port > 0 else ANYLLM_DEFAULT_PORT


def anyllm_is_running(config: Dict[str, object]) -> bool:
    port = _port(config)
    url = f"http://127.0.0.1:{port}{ANYLLM_HEALTH_PATH}"
    try:
        with urllib.request.urlopen(url, timeout=_HEALTH_TIMEOUT) as resp:
            return resp.getcode() == 200 and b'"status"' in resp.read(256)
    except (urllib.error.URLError, OSError, ValueError):
        # No /health answer: a bound port still means something owns 3000.
        return _port_open(port)


def _port_open(port: int) -> bool:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.3)
    try:
        sock.connect(("127.0.0.1", port))
        return True
    except OSError:
        return False
    finally:
        sock.close()


def _admin_token_path() -> Path:
    override = os.environ.get("ADMIN_TOKEN_PATH")
    if override and override.strip():
        return Path(override).expanduser()
    home = os.environ.get("ANYLLM_HOME")
    base = Path(home).expanduser() if home and home.strip() else Path.home() / ".anyllm"
    return base / ".admin_token"


def resolve_admin_token() -> Tuple[Optional[str], str]:
    """Return (token, source). Honors ADMIN_TOKEN, else reads the token file."""
    token = os.environ.get("ADMIN_TOKEN")
    if token and token.strip():
        return token.strip(), "ADMIN_TOKEN env"
    path = _admin_token_path()
    try:
        text = path.read_text(encoding="utf-8").strip()
    except OSError:
        return None, str(path)
    return (text or None), str(path)


def anyllm_admin_url(config: Dict[str, object], token: Optional[str] = None) -> str:
    base = str(config.get("adminUrl") or ANYLLM_DEFAULT_ADMIN_URL)
    if not token:
        return base
    # anyllm-proxy 0.13.0+ auto-logs-in from ?token=; older versions ignore it.
    sep = "&" if "?" in base else "?"
    return f"{base}{sep}token={token}"


def _pid_path(config: Dict[str, object]) -> Optional[Path]:
    text = str(config.get("pidFilePath") or "").strip()
    return Path(text) if text else None


def _write_pid(config: Dict[str, object], pid: int) -> None:
    path = _pid_path(config)
    if path is None:
        return
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(str(pid), encoding="utf-8")
    except OSError:
        pass


def _read_pid(config: Dict[str, object]) -> Optional[int]:
    path = _pid_path(config)
    if path is None:
        return None
    try:
        return int(path.read_text(encoding="utf-8").strip())
    except (OSError, ValueError):
        return None


def _clear_pid(config: Dict[str, object]) -> None:
    path = _pid_path(config)
    if path is None:
        return
    try:
        path.unlink()
    except OSError:
        pass


def start_anyllm(config: Dict[str, object], *, wait: float = _START_WAIT_SECONDS) -> AnyllmResult:
    port = _port(config)
    log_path = str(config.get("logPath") or "")
    if anyllm_is_running(config):
        return AnyllmResult("start", True, True, _read_pid(config), f"AnyLLM proxy already running on 127.0.0.1:{port}; reusing it.", log_path)
    binary = find_anyllm_proxy_binary() or str(config.get("binary") or "").strip()
    if not binary:
        return AnyllmResult("start", False, False, None, "anyllm-proxy binary not found (brew install whit3rabbit/tap/anyllm-proxy).", log_path)
    key = str(config.get("key") or "").strip()
    if not key:
        return AnyllmResult("start", False, False, None, "AnyLLM proxy key missing from the variant manifest.", log_path)
    args = [str(a) for a in (config.get("args") or [])]
    env = dict(os.environ)
    # Same inbound key the wrapper exports, so Claude's ANTHROPIC_AUTH_TOKEN matches.
    env["PROXY_API_KEYS"] = key
    env["LISTEN_PORT"] = str(port)

    log_handle = None
    stdout = subprocess.DEVNULL
    if log_path:
        Path(log_path).parent.mkdir(parents=True, exist_ok=True)
        log_handle = open(log_path, "ab")
        stdout = log_handle
    try:
        proc = subprocess.Popen(
            [binary, *args],
            env=env,
            stdout=stdout,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
    finally:
        if log_handle is not None:
            log_handle.close()

    _write_pid(config, proc.pid)
    deadline = time.monotonic() + wait
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            _clear_pid(config)
            return AnyllmResult("start", False, False, None, f"AnyLLM proxy exited early (code {proc.returncode}). See {log_path}", log_path)
        if anyllm_is_running(config):
            return AnyllmResult("start", True, True, proc.pid, f"AnyLLM proxy started on 127.0.0.1:{port}.", log_path)
        time.sleep(0.2)
    return AnyllmResult("start", False, False, proc.pid, f"AnyLLM proxy did not become ready on 127.0.0.1:{port}. See {log_path}", log_path)


def stop_anyllm(config: Dict[str, object]) -> AnyllmResult:
    pid = _read_pid(config)
    running = anyllm_is_running(config)
    if pid is None:
        if running:
            return AnyllmResult("stop", False, True, None, "AnyLLM proxy is running but was not started by ccsilo; stop it where you launched it.")
        return AnyllmResult("stop", True, False, None, "AnyLLM proxy is not running.")
    try:
        os.kill(pid, signal.SIGTERM)
    except ProcessLookupError:
        _clear_pid(config)
        return AnyllmResult("stop", True, False, None, "AnyLLM proxy was already stopped.")
    except OSError as exc:
        return AnyllmResult("stop", False, running, pid, f"Failed to stop AnyLLM proxy (pid {pid}): {exc}")
    deadline = time.monotonic() + _STOP_WAIT_SECONDS
    while time.monotonic() < deadline:
        try:
            os.kill(pid, 0)
        except OSError:
            break
        time.sleep(0.2)
    _clear_pid(config)
    return AnyllmResult("stop", True, False, None, f"Stopped AnyLLM proxy (pid {pid}).")


def restart_anyllm(config: Dict[str, object]) -> AnyllmResult:
    stop_anyllm(config)
    result = start_anyllm(config)
    result.action = "restart"
    return result


def anyllm_status(config: Dict[str, object]) -> AnyllmResult:
    running = anyllm_is_running(config)
    pid = _read_pid(config) if running else None
    token, source = resolve_admin_token()
    port = _port(config)
    detail = f"AnyLLM proxy running on 127.0.0.1:{port}." if running else "AnyLLM proxy is stopped."
    detail += f" Admin token: {'available (' + source + ')' if token else 'not found (created on first run)'}."
    return AnyllmResult("status", True, running, pid, detail)


def anyllm_doctor_checks(manifest: Dict) -> List[Dict[str, object]]:
    """Informational checks for the AnyLLM managed proxy.

    Both checks report ok=True: the proxy is on-demand (the wrapper launches it
    per run), and the admin token legitimately does not exist until first run, so
    neither state should turn a fresh setup's health red. The binary/port checks
    in ``_local_proxy_doctor_checks`` remain the real pass/fail signal.
    """
    config = anyllm_proxy_config(manifest)
    if config is None:
        return []
    token, source = resolve_admin_token()
    running = anyllm_is_running(config)
    return [
        {
            "name": "anyllm-admin-token",
            "ok": True,
            "path": source,
            "detail": f"available ({source})" if token else "created on first run at ~/.anyllm/.admin_token",
        },
        {
            "name": "anyllm-running",
            "ok": True,
            "path": f"http://127.0.0.1:{_port(config)}{ANYLLM_HEALTH_PATH}",
            "detail": "running" if running else "stopped (started on demand)",
        },
    ]
