"""Provider templates and env builders for alternate Claude Code backends."""

from .config import (
    PLACEHOLDER_CREDENTIAL,
    ProviderConfigResult,
    apply_provider_claude_config,
    ensure_onboarding_state,
    provider_auth_bootstrap_enabled,
)
from .loader import (
    build_provider_env,
    get_provider,
    list_providers,
    provider_claude_config,
    provider_default_variant_name,
    provider_patch_config,
    provider_prompt_overlays,
    provider_theme,
)
from .model_discovery import (
    fetch_provider_models,
    parse_model_ids,
    provider_models_url,
)
from .mcp_catalog import (
    PLUGIN_RECOMMENDATIONS,
    McpCatalogEntry,
    list_mcp_catalog,
    list_optional_mcp_entries,
    mcp_entry_payload,
    normalize_mcp_ids,
    optional_mcp_servers,
)
from .local_integrations import (
    ANYLLM_PROXY_ID,
    CONTEXT7_ID,
    KNOWN_LOCAL_INTEGRATION_IDS,
    RTK_ID,
    LocalIntegrationInstallResult,
    LocalIntegrationStatus,
    detect_anyllm_proxy,
    detect_local_integrations,
    find_anyllm_proxy_binary,
    install_anyllm_proxy,
    install_local_integration,
    normalize_integration_ids,
    sync_local_integrations,
)
from .schema import DEFAULT_TIMEOUT_MS, MODEL_ENV_KEYS, ProviderEnv, ProviderSchemaError, ProviderTemplate

__all__ = [
    "ANYLLM_PROXY_ID",
    "CONTEXT7_ID",
    "DEFAULT_TIMEOUT_MS",
    "KNOWN_LOCAL_INTEGRATION_IDS",
    "MODEL_ENV_KEYS",
    "PLACEHOLDER_CREDENTIAL",
    "PLUGIN_RECOMMENDATIONS",
    "RTK_ID",
    "LocalIntegrationInstallResult",
    "LocalIntegrationStatus",
    "McpCatalogEntry",
    "ProviderConfigResult",
    "ProviderEnv",
    "ProviderSchemaError",
    "ProviderTemplate",
    "apply_provider_claude_config",
    "build_provider_env",
    "detect_anyllm_proxy",
    "detect_local_integrations",
    "ensure_onboarding_state",
    "find_anyllm_proxy_binary",
    "get_provider",
    "install_anyllm_proxy",
    "install_local_integration",
    "list_mcp_catalog",
    "list_optional_mcp_entries",
    "list_providers",
    "mcp_entry_payload",
    "normalize_integration_ids",
    "normalize_mcp_ids",
    "optional_mcp_servers",
    "provider_claude_config",
    "provider_auth_bootstrap_enabled",
    "provider_default_variant_name",
    "provider_patch_config",
    "provider_prompt_overlays",
    "provider_theme",
    "fetch_provider_models",
    "parse_model_ids",
    "provider_models_url",
    "sync_local_integrations",
]
